# yaml-language-server: $schema=https://raw.githubusercontent.com/release-drafter/release-drafter/master/schema.json

# NOTES:
# - The value of the `version` action input is NOT made directly available to this template.
# - Components like $MAJOR/$MINOR/$PATCH are derived either by parsing the `version` action input
#   or else computed by incrementing the previous release if no `version` input is given.
# - $RESOLVED_VERSION is the result of rendering the below `version-template` config value
#   once the individual version number components have been derived.
# - We compute our YYYY.inc versions separately and passed the result as `version` input;
#   while it is NOT incremented by this action, it is still parsed into components, where:
#   - $MAJOR = YYYY value of `version` input
#   - $MINOR = inc value of `version` input
#   - $PATCH will always be 0 (and is not used in this template)

version-template: '$MAJOR.$MINOR'
name-template: 'v$RESOLVED_VERSION'
tag-template: 'release/$RESOLVED_VERSION'
tag-prefix: 'release/'
version-resolver:
  default: minor
prerelease: true
include-pre-releases: false
categories:
  - title: 🚀 New features and enhancements
    collapse-after: 10
    labels:
      - enhancement
  - title: 🐛 Bug fixes
    collapse-after: 10
    labels:
      - bug
  - title: 📖 Documentation improvements
    collapse-after: 10
    labels:
      - documentation
  - title: 🔧 Dependency updates
    collapse-after: 3
    labels:
      - dependencies
  - title: Other Changes
    labels:
      - '*'
category-template: '### $TITLE'
exclude-labels:
  - skip-changelog
autolabeler:
  - label: go
    files:
      - '**/*.go'
      - go.mod
      - go.sum
  - label: terraform
    files:
      - 'terraform/**'
  - label: dependencies
    files:
      - go.mod
      - go.sum
      - '**/.terraform.lock.hcl'
    branch:
      - '/dependabot\/.+/'
  - label: documentation
    files:
      - README
      - '**/doc/**'
      - '**/docs/**'
      - '**/*.md'
    branch:
      - '/docs?/'
  - label: bug
    branch:
      - '/fix\/.+/'
      - '/bug\/.+/'
    title:
      - '/\bfix(es)?\b/i'
      - '/\bbug\b/i'
  - label: enhancement
    branch:
      - 'feat(ure)?\/.+/'
      - 'enhance(s|ment)?\/.+/'
    title:
      - '/\bfeat(ure)?\b/i'
      - '/\benhance(s|ment)?\b/i'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'
template: |
  ## 📚 Summary

  The releaser should provide a high-level summary here (or remove this section).

  ## 🛠️ Changes

  $CHANGES

  ## 🤝 Contributors

  We would like to thank the following people who made this release possible:

  $CONTRIBUTORS

  ## Deployment History
