name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
categories:
changelog:
  - title: 🚀 New features and enhancements
    labels:
      - enhancement
  - title: 🐛 Bug fixes
    labels:
      - bug
  - title: 📖 Documentation improvements
    labels:
      - documentation
  - title: 🔧 Dependency updates
    labels:
      - dependencies
  - title: Other Changes
    labels:
      - "*"
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Changes

  $CHANGES
