name: Release Drafter

on:
  push:
    branches:
      - main
  pull_request_target:
    types: [opened, reopened, synchronize]
  workflow_dispatch:
    inputs:
      inspect_latest_release:
        description: >-
          Whether to compute the next release version using the latest release tag.
          If false, computes the next release version using the most-recent release tag on `main`.
        type: boolean
        default: true

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: crazy-max/ghaction-dump-context@v2
      - uses: actions/checkout@v3
        with:
          ref: main
      - name: Get tag of latest release
        id: latest_release
        if: github.event_name != 'workflow_dispatch' || inputs.inspect_latest_release
        run: echo "tag=$(gh release view --json tagName --jq .tagName)" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "Determine next release version"
        id: next_release
        run: |
          chmod +x .github/next_release_version.bash
          echo "version=$(bash .github/next_release_version.bash $LATEST_TAG)" >> $GITHUB_OUTPUT
        env:
          LATEST_TAG: ${{ steps.latest_release.outputs.tag || '' }}
      - uses: release-drafter/release-drafter@b1476f6e6eb133afa41ed8589daba6dc69b4d3f5 # v6.1.0
        with:
          version: ${{ steps.next_release.outputs.version }}
          publish: false
          disable-releaser: false
          disable-autolabeler: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
