name: Rotate a secret

on:
  push:
  schedule:
    - cron: '*/5 * * * *'

permissions: write-all

jobs:
  do:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v3
      - name: Debug auth
        run: gh auth status
      - name: More debug
        run: |
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ env.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/TylerHendrickson/releasemporium/actions/secrets/public-key
      - name: Create the secret
        if: always
        run: openssl rand -hex 1024 > newsecret
      - name: Set the secret
        if: always
        run: gh -R TylerHendrickson/releasemporium secret set MyRotatedWorkflowSecret --app actions < newsecret
        env:
          GH_TOKEN: ${{ github.token }}
