name: Rotate a secret

on:
  push:
  schedule:
    - cron: '*/5 * * * *'

permissions: write-all

jobs:
  do:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v3
      - name: Debug auth
        run: gh auth status
      - run: gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28"
  /repos/OWNER/REPO/actions/secrets/public-key
      - name: Create the secret
        run: openssl rand -hex 1024 > newsecret
      - name: Set the secret
        run: gh -R TylerHendrickson/releasemporium secret set MyRotatedWorkflowSecret --app actions < newsecret
        env:
          GH_TOKEN: ${{ github.token }}
